/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wejhati_280;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author macbook
 */
public class Activities extends javax.swing.JFrame {
FileWriter f;
    /**
     * Creates new form Activities
     * @throws java.io.IOException
     */
    public Activities() throws IOException {
   
        f=new FileWriter("Activity.txt");
        initComponents();
        setLocationRelativeTo(null);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        jLabel10.setText("Sleep in a Bedouin  ");

        jLabel12.setText("  at Wadi Rum");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(369, 660));
        getContentPane().setLayout(null);

        jLabel11.setText("Sleep in a Bedouin  ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 190, 146, 16);

        jLabel13.setText("  at Wadi Rum");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 210, 86, 16);

        jLabel14.setText("  Camp in Wadi Rum");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(200, 210, 126, 16);

        jLabel16.setText("Enjoy Desert Safari ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(210, 190, 122, 16);

        jLabel15.setText("Spend a Night Under  ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 350, 137, 16);

        jLabel17.setText(" the Stars in Wadi Rum ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 370, 145, 16);

        jLabel18.setText("Road Trip The King’s Highway");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(170, 350, 188, 16);

        jLabel19.setText("Canyoning at Wadi al-Mujib");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 520, 175, 29);

        jLabel20.setText("Sleep in a Bedouin  ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(210, 520, 122, 16);

        jLabel21.setText("Camp in Wadi Rum");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(210, 540, 118, 16);

        jLabel2.setFont(new java.awt.Font("SF Movie Poster", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Wejhati");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 20, 200, 40);

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 80, 380, 12);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/bar_icon.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 20, 85, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/Activity1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 160, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/Activity2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 80, 170, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/Activity3.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 250, 170, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/Activity4.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 260, 190, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/Activity5.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 410, 170, 108);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/Activity6.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 410, 180, 110);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/ADD_icon.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 220, 34, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/ADD_icon.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(250, 220, 34, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/ADD_icon.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(70, 380, 34, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/ADD_icon.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24);
        jLabel24.setBounds(250, 380, 34, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/ADD_icon.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25);
        jLabel25.setBounds(70, 550, 34, 39);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/ADD_icon.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26);
        jLabel26.setBounds(260, 560, 34, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/back_icon.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27);
        jLabel27.setBounds(10, 570, 78, 100);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/next_icon.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28);
        jLabel28.setBounds(210, 600, 146, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/gradient.jpg"))); // NOI18N
        jLabel29.setPreferredSize(new java.awt.Dimension(369, 705));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(0, -130, 390, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
               try {
        // TODO add your handling code here:
        f.write(jLabel11.getText().trim()+jLabel13.getText()+"\n");
      
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/confirm.png"));
        JOptionPane.showMessageDialog(this, "The Activity added successfully", "Confirm Message", JOptionPane.INFORMATION_MESSAGE,icon);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
               try {
        // TODO add your handling code here:
        f.write(jLabel16.getText().trim()+jLabel14.getText()+"\n");
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/confirm.png"));
        JOptionPane.showMessageDialog(this, "The Activity added successfully", "Confirm Message", JOptionPane.INFORMATION_MESSAGE,icon);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
               try {
        // TODO add your handling code here:
        f.write(jLabel15.getText().trim()+jLabel17.getText()+"\n");
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/confirm.png"));
        JOptionPane.showMessageDialog(this, "The Activity added successfully", "Confirm Message", JOptionPane.INFORMATION_MESSAGE,icon);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
               try {
        // TODO add your handling code here:
        f.write(jLabel18.getText()+"\n");
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/confirm.png"));
        JOptionPane.showMessageDialog(this, "The Activity added successfully", "Confirm Message", JOptionPane.INFORMATION_MESSAGE,icon);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
               try {
        // TODO add your handling code here:
        f.write(jLabel19.getText()+"\n");
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/confirm.png"));
        JOptionPane.showMessageDialog(this, "The Activity added successfully", "Confirm Message", JOptionPane.INFORMATION_MESSAGE,icon);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
               try {
        // TODO add your handling code here:
        f.write(jLabel20.getText().trim()+jLabel21.getText()+"\n");
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/confirm.png"));
        JOptionPane.showMessageDialog(this, "The Activity added successfully", "Confirm Message", JOptionPane.INFORMATION_MESSAGE,icon);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
           try {
        // TODO add your handling code here:
        f.close();
        menu2 sn=new menu2();
        sn.setVisible(true);
    } catch (IOException ex) {
        Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
          confirmpaln sn;
        sn = new confirmpaln();
        sn.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Activities().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Activities.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
