/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wejhati_280;

import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;


/**
 *
 * @author manar
 */
public class reset_password extends javax.swing.JFrame {
static FileWriter fw;
static String newPass;
    /**
     * Creates new form reset_password
     */
    public reset_password() {
        initComponents();   setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        password = new javax.swing.JTextField();
        send = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        confirm_newpass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 630));
        getContentPane().setLayout(null);

        username.setBorder(null);
        getContentPane().add(username);
        username.setBounds(20, 210, 270, 20);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 230, 270, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 280, 270, 20);

        password.setBorder(null);
        getContentPane().add(password);
        password.setBounds(20, 260, 270, 20);

        send.setBackground(new java.awt.Color(0, 0, 0));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SF Movie Poster", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("send");

        javax.swing.GroupLayout sendLayout = new javax.swing.GroupLayout(send);
        send.setLayout(sendLayout);
        sendLayout.setHorizontalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel7)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        sendLayout.setVerticalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(send);
        send.setBounds(80, 420, 170, 50);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 330, 270, 20);

        confirm_newpass.setBorder(null);
        getContentPane().add(confirm_newpass);
        confirm_newpass.setBounds(20, 310, 270, 20);

        jLabel5.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("confirm new password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 290, 300, 20);

        jLabel6.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("new password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 240, 300, 20);

        jLabel3.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("password length must be 7 including");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 260, 40);

        jLabel8.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 190, 300, 20);

        jLabel4.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("charcaters and numbers");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 130, 260, 40);

        jLabel2.setFont(new java.awt.Font("SF Movie Poster", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("reset your password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 50, 290, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/gradient.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        sign_in sn;
       File login = new File("login.txt");

        int checkStrength=0;
        int checkMatch=0;
        String line [] = new String [10];
        try {
            File file = new File("login.txt");
            Scanner read;
            int usernameCheck=0;
          
                if("imneell".equals(username.getText())){

                    usernameCheck=1;
                }else{
                    usernameCheck=0;
                }
            
            if(usernameCheck==0){

                UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                    "SF Movie Poster", Font.BOLD, 20)));
        final JOptionPane pane = new JOptionPane("the username is wrong,"+"\n"+"please try again to reset the password");
        final JDialog d = pane.createDialog((JFrame)null, "");
        d.setLocation(530,300);
        d.setVisible(true);
        }
        if(usernameCheck==1&&password.getText().length()>=7 && username.getText().matches("^[a-zA-Z0-9]*$") ){
            checkStrength=1;
        }
        else{
            checkStrength=0;

        }
        if(usernameCheck==1&&checkStrength==1) {
            if(password.getText().equals(confirm_newpass.getText())){
                checkMatch=1;
            }else{
                checkMatch=0;
                UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                    "SF Movie Poster", Font.BOLD, 20)));
        final JOptionPane pane = new JOptionPane("password doesn't match the new password");
        final JDialog d = pane.createDialog((JFrame)null, "");   d.setLocation(530,300);
        d.setVisible(true);
        }
        }

        if(checkMatch==1){
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "SF Movie Poster", Font.BOLD, 20)));
    final JOptionPane pane = new JOptionPane("new password is confiremed");

    final JDialog d = pane.createDialog((JFrame)null, "Confirmation");   d.setLocation(530,300);
    d.setVisible(true);
    sn = new sign_in();
    sn.setVisible(true);
    reset_password res = new  reset_password();
    String newPass1 = res.newPass();
    sign_up sp = new sign_up();
    signup spp = new signup("b",sp.getUsername(),newPass1,"o","p","p","k");
    sign_linkedlist s = new sign_linkedlist();
    //s.removeStudent(username.getText());
    s.addUser(spp);
    spp.setPassword(newPass1);
    fw.write(s.PrintInfo());
    }
    if(checkStrength==0 && usernameCheck==1){
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "SF Movie Poster", Font.BOLD, 20)));
final JOptionPane pane = new JOptionPane("password too weak");
final JDialog d = pane.createDialog((JFrame)null, "");   d.setLocation(50,300);
d.setVisible(true);
}

} catch (FileNotFoundException ex) {
    Logger.getLogger(reset_password.class.getName()).log(Level.SEVERE, null, ex);} catch (IOException ex) {
    Logger.getLogger(reset_password.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_sendMouseClicked
                            
public boolean isMatched(){
    return (password.getText().equals(confirm_newpass.getText()));
}
public String newPass(){
    if(isMatched()==true){
        return password.getText();
    }
    return null;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm_newpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField password;
    private javax.swing.JPanel send;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
