/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wejhati_280;
import java.awt.Color;
import java.io.File;import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author manar
 */
public class sign_up extends javax.swing.JFrame {
static String user;
static String pass;
static File login;
static FileWriter fw;
static int count;
static int clicked;
boolean isMale;
boolean isFemale;
static signup su;
    /** Creates new form sign_up */
    public sign_up() throws IOException {
        initComponents();     
        login = new File("login.txt");
         fw = new FileWriter(login,true);   
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        countrycode = new javax.swing.JComboBox<>();
        phoneno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        male = new javax.swing.JCheckBox();
        female = new javax.swing.JCheckBox();
        cancel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        confirm = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 630));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SF Movie Poster", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("sign up");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 150, 40);

        jLabel17.setFont(new java.awt.Font("SF Movie Poster", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("must be all numeric");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 190, 90, 15);

        countrycode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "966", "962", "83", "81", "967", "212", "955" }));
        getContentPane().add(countrycode);
        countrycode.setBounds(40, 210, 60, 30);

        phoneno.setText("XX-XXX-XXXX");
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });
        getContentPane().add(phoneno);
        phoneno.setBounds(110, 210, 210, 30);

        jLabel12.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("username");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 390, 80, 20);

        jLabel7.setFont(new java.awt.Font("SF Movie Poster", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("+");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 220, 20, 10);
        getContentPane().add(country);
        country.setBounds(10, 350, 90, 30);
        getContentPane().add(lname);
        lname.setBounds(10, 150, 90, 30);

        dob.setText("DD/MM/YYYY");
        getContentPane().add(dob);
        dob.setBounds(10, 280, 310, 30);
        getContentPane().add(username);
        username.setBounds(10, 420, 130, 30);
        getContentPane().add(password);
        password.setBounds(170, 420, 130, 30);

        jLabel10.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("gender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 460, 80, 20);

        jLabel3.setFont(new java.awt.Font("SF Movie Poster", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("must be 7 including charcaters and numbers");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 370, 200, 15);

        male.setSelected(true);
        male.setText("male");
        getContentPane().add(male);
        male.setBounds(30, 490, 60, 23);

        female.setSelected(true);
        female.setText("female");
        getContentPane().add(female);
        female.setBounds(180, 490, 70, 23);

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("SF Movie Poster", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("cancel");

        javax.swing.GroupLayout cancelLayout = new javax.swing.GroupLayout(cancel);
        cancel.setLayout(cancelLayout);
        cancelLayout.setHorizontalGroup(
            cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        cancelLayout.setVerticalGroup(
            cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(cancel);
        cancel.setBounds(30, 530, 110, 50);

        jLabel9.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Country");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 320, 300, 20);

        jLabel11.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("password");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(200, 390, 80, 20);

        confirm.setBackground(new java.awt.Color(255, 255, 255));
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("SF Movie Poster", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("confirm");

        javax.swing.GroupLayout confirmLayout = new javax.swing.GroupLayout(confirm);
        confirm.setLayout(confirmLayout);
        confirmLayout.setHorizontalGroup(
            confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(33, 33, 33))
        );
        confirmLayout.setVerticalGroup(
            confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(confirm);
        confirm.setBounds(170, 530, 120, 50);

        jLabel8.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Date ob birth");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 250, 300, 20);

        jLabel6.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("phone number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 190, 80, 20);

        jLabel15.setFont(new java.awt.Font("SF Movie Poster", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("must be all in alphates");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(110, 160, 130, 15);

        jLabel5.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("last name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 300, 20);

        jLabel4.setFont(new java.awt.Font("SF Movie Poster", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("first name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 60, 300, 30);

        jLabel16.setFont(new java.awt.Font("SF Movie Poster", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("must be all in alphates");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 100, 130, 15);
        getContentPane().add(fname);
        fname.setBounds(10, 90, 90, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 330, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wejhati_280/gradient.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 420, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String isGender (){
    if(isMale==true){
        return "Male";
    }
    return "Female";
}
public String getUsername(){
    return username.getText();
}
    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked

        isMale = male.isSelected();
        isFemale = female.isSelected();
        int match=0;
        int date=0;
        String gender = isGender();
        int checkStrength=0;
        if(phoneno.getText().matches("\\d{2}-\\d{3}-\\d{4}")){
            match=1;
        }else{
            match=0;
        }
        int same=0;
        File file = new File ("login.txt");
        Scanner  read;
        try {
            read = new Scanner (file);
            while(read.hasNext()){
                String line [] = read.next().split(",");
                if(line[1].equals(username.getText())){
                    same=1;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(isFemale==true && isMale==true){
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "SF Movie Poster", Font.BOLD, 20)));
    final JOptionPane pane = new JOptionPane("Please choose only male or female");
    final JDialog d = pane.createDialog((JFrame)null, "");
    d.setLocation(50,300);
    d.setVisible(true);
    }else{
        try {
            sign_linkedlist snll = new sign_linkedlist();
            su = new signup (country.getText(), username.getText(),password.getText(),  gender, phoneno.getText(), fname.getText(), lname.getText());
            snll.addUser(su);
            /*  fw.write("username,"+username.getText()+","+"password"+","+password.getText() +","+"Gender" +","+ gender+ ","  + "," + "country"+","+country.getText()+"," +
                "first" + fname.getText()+"," + "last" +"," + lname.getText()+","+countrycode.getSelectedItem()+"," + "phoneNo"
                +"," + phoneno.getText()+"\n"); fw.close();*/
            fw.write(snll.PrintInfo());fw.close();
        } catch (IOException ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(password.getText().length()>=7 && username.getText().matches("^[a-zA-Z0-9]*$") ){
            checkStrength=1;
        }
        else{
            checkStrength=0;
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "SF Movie Poster", Font.BOLD, 20)));
    final JOptionPane pane = new JOptionPane("pasword is too weak");
    final JDialog d = pane.createDialog((JFrame)null, "Confirmation");
    d.setLocation(50,300);
    d.setVisible(true);
    }
    if(same==0&&match==1&&checkStrength==1){
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "SF Movie Poster", Font.BOLD, 20)));
final JOptionPane pane = new JOptionPane("Data is stored");
final JDialog d = pane.createDialog((JFrame)null, "Confirmation");
d.setLocation(50,300);
d.setVisible(true);
country.setText(null);
fname.setText(null);
lname.setText(null);
phoneno.setText(null);
dob.setText(null);
username.setText(null);
password.setText(null);
male.disable();
female.disable();
menu1 men = new menu1 ();
men.setVisible(true);  }
if(match==0){
    UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
        "SF Movie Poster", Font.BOLD, 20)));
        final JOptionPane pane = new JOptionPane("please enter the phone number again as required");
        final JDialog d = pane.createDialog((JFrame)null, "");
        d.setLocation(50,300);
        d.setVisible(true);
        phoneno.setText("XX-XXX-XXXX");
        }
        if(same==1){
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "SF Movie Poster", Font.BOLD, 20)));
    final JOptionPane pane = new JOptionPane("sorry the username exits");
    final JDialog d = pane.createDialog((JFrame)null, "");
    d.setLocation(50,300);
    d.setVisible(true);
    }
    /*else{
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "SF Movie Poster", Font.BOLD, 20)));
final JOptionPane pane = new JOptionPane("Sorry, please enter  the data");
final JDialog d = pane.createDialog((JFrame)null, "");
d.setLocation(50,300);
d.setVisible(true);
}*/
}
    }//GEN-LAST:event_confirmMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked

    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new sign_up().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel;
    private javax.swing.JPanel confirm;
    private javax.swing.JTextField country;
    private javax.swing.JComboBox<String> countrycode;
    private javax.swing.JTextField dob;
    private javax.swing.JCheckBox female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lname;
    private javax.swing.JCheckBox male;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
